keyword = "break" / "case" / "continue" / "do" / "else" / "for" 
keyword /= "goto" / "if" / "return" / "switch" / "while"

typeSpecifier = "bool" / "boolean" / "byte" / "char" / "double" / "float" / "int"
typeSpecifier /= "long" / "short" / "size_t" / "void" / "word" / "unsigned" 
unsigned_type = "unsigned int" / "unsigned char" / "unsigned long"

typeQualifier = "const" / "volatile"
storageClassSpecifier = "static"
typeSpecifier = type / unsigned_type

; translation unit

sketch = *sketchItem EOF

sketchItem = declaration ";"
sketchItem /= statement

; declarations

declaration = declSpecifiers declaratorList

declSpecifiers  = storageClassSpecifier [declSpecifiers]
declSpecifiers /= typeSpecifier [declSpecifiers]
declSpecifiers /= typeQualifier [declSpecifiers]

declaratorList = declarator *("," declarator)

declarator = [pointer] directDeclarator

directDeclarator  = ident (variableDeclarator / functionDeclarator)

variableDeclarator = *( "[" [int] "]" ) ["=" initializer]
functionDeclarator = "(" paramList ")" "{" 1*statement "}"

pointer  = "*" [typeQualifierList]
pointer /= "*" [typeQualifierList] pointer

typeQualifierList = typeQualifier *(typeQualifier)

paramList = param *("," param)
param = declSpecifiers declarator

; statements

statement  = exprStmt
statement /= returnStmt
statement /= breakStmt
statement /= ifStmt
statement /= blockStmt
statement /= switchStmt
statement /= forStmt

varDecl = declStart ["=" initializer] ";"
fnDecl  = declStart "(" params ")" "{" +statement "}"
declStart = (type / unsigned_type) [array_def] identifier

initializer  = assignExpr
initializer /= "{" initializer *("," initializer) [","] "}"

exprStmt = expr ";"
returnStmt = "return" expr ";"
breakStmt = "break" ";"
ifStmt = "if" "(" expr ")" blockStmt ["else" blockStmt]
blockStmt = "{" *declaration "}"
switchStmt = "switch" "(" expr ")" "{" *caseStmt "}"
caseStmt = "case" int ":" *statement
caseStmt /= "default" ":" *statement
forStmt = "for" "(" (varDecl / exprStmt / ";") [expr] ";" [expr] ")" statement 

array_def = "[" +DIGIT "]"

params = *declStart *("," declStart)
; expressions

expr = binaryExpr
expr /= unaryExpr
expr /= literalExpr
expr /= variableExpr
expr /= assignExpr
expr /= callExpr

callExpr = variableExpr "(" argList? ")"

argList = expr *( "," expr )

assignExpr = ident "=" expr
variableExpr = ident

unaryExpr  = postfixExpr
unaryExpr /= "++" unaryExpr
unaryExpr /= "--" unaryExpr
unaryExpr /= unaryOp castExpr
unaryExpr /= "sizeof" unaryExpr
unaryExpr /= "sizeof" "(" typeSpecifier ")"

unaryOp = "&" / "*" / "+" / "-" / "~" / "!"

postfixExpr = primaryExpr *postfixExprP

postfixExprP = *( "[" expr "]" ) ; array access
postfixExprP = "(" [argList] ")" ; callExpr
postfixExprP = "--"              ; postfix decrement
postfixExprP = "++"              ; postfix increment

primaryExpr  = ident
primaryExpr /= constant

constant = int / str / float
; literalExpr = int / str / ident / "true" / "false" / "HIGH" / "LOW"

int = 1*DIGIT
float = 1*DIGIT "." 1*DIGIT
str = DQUOTE *(%x20-21 / %x23-7E) DQUOTE
      ; quoted string of SP and VCHAR
      ;  without DQUOTE
ident = ALPHA *(ALPHA / DIGIT / "-" / "_")
