keyword = "break" / "case" / "continue" / "do" / "else" / "for" 
keyword /= "goto" / "if" / "return" / "switch" / "while"

type = "bool" / "boolean" / "byte" / "char" / "double" / "float" / "int"
type /= "long" / "short" / "size_t" / "void" / "word" 

unsigned_type = "unsigned int" / "unsigned char" / "unsigned long"

declaration  = classDecl
declaration  = varDecl
declaration /= fnDecl
declaration /= statement

statement  = exprStmt
statement /= returnStmt
statement /= breakStmt
statement /= ifStmt
statement /= blockStmt
statement /= switchStmt
statement /= forStmt

varDecl = declStart ["=" initializer] ";"
fnDecl  = declStart "(" params ")" "{" +statement "}"
declStart = (type / unsigned_type) [array_def] identifier

initializer = expr

exprStmt = expr ";"
returnStmt = "return" expr ";"
breakStmt = "break" ";"
ifStmt = "if" "(" expr ")" blockStmt ["else" blockStmt]
blockStmt = "{" *declaration "}"
switchStmt = "switch" "(" expr ")" "{" *caseStmt "}"
caseStmt = "case" int ":" *statement
caseStmt /= "default" ":" *statement
forStmt = "for" "(" (varDecl / exprStmt / ";") [expr] ";" [expr] ")" statement 

array_def = "[" +DIGIT "]"

params = *declStart *("," declStart)

expr = binaryExpr
expr /= unaryExpr
expr /= literalExpr
expr /= variableExpr
expr /= assignExpr
expr /= callExpr

callExpr = variableExpr "(" arguments? ")"

arguments = expr *( "," expr )

literalExpr = int / str / ident / "true" / "false" / "HIGH" / "LOW"
assignExpr = ident "=" expr
variableExpr = ident
